import fs from "node:fs";
import path from "node:path";
import type { NextConfig } from "next";

/**
 * The old-URL map. 221 rows and 26 "gone" patterns covering all 797 URLs in the old
 * WordPress sitemap, generated by `scripts/build-redirects.mjs` from the content and
 * taxonomy data — never edited here, or the next content change silently invalidates it.
 * Read as a file rather than imported so the config does not depend on JSON module
 * resolution in whichever bundler loads it.
 */
type RedirectRow = {
  source: string;
  destination: string;
  statusCode: number;
  has?: { type: "header" | "cookie" | "query"; key: string; value?: string }[];
  /** Set on the six WooCommerce basket/checkout/account paths. See SHOP_URL below. */
  shopOrigin?: string;
};

const map = JSON.parse(
  fs.readFileSync(path.join(process.cwd(), "content/data/redirects.json"), "utf8"),
) as { redirects: RedirectRow[]; gone: string[] };

/**
 * THE ONE THING THAT BREAKS THE SHOP.
 *
 * Every buy button on this site sends the customer to
 * `https://www.jessecaron.com/product/<slug>/` — the live WooCommerce store — because
 * this site has no basket and no checkout of its own. That is fine today, because this
 * site is on a different host.
 *
 * The moment `www.jessecaron.com` points at this deployment, those buttons point at
 * *this* site, the row above turns them into a 301 back to `/shop/<slug>`, and the
 * customer walks in a circle. There is no error, no 404, nothing in a log: the shop
 * simply stops taking money.
 *
 * So the shop's origin is a setting, and there is a build-time guard that refuses to
 * ship a site whose shop origin is its own hostname (`scripts/check-shop-links.mjs`,
 * run by `prebuild`). Set `NEXT_PUBLIC_SHOP_URL=https://shop.jessecaron.com` in Vercel
 * BEFORE DNS moves — the order is not optional. See `docs/DOMAIN-MOVE.md`.
 */
const SHOP_URL = process.env.NEXT_PUBLIC_SHOP_URL?.replace(/\/+$/, "");

const nextConfig: NextConfig = {
  /**
   * YouTube video thumbnails are the one remote image the site renders. Without this
   * host on the allow-list `next/image` refuses them, which is why VideoFacade was
   * shipped with `unoptimized` — the 16:9 box was reserved, but YouTube's bytes came
   * through untouched. Allow-listing the host lets the optimiser resize and re-encode
   * them like everything else. It is scoped to that one hostname deliberately: a
   * wildcard here turns the image endpoint into an open proxy for any URL a page can
   * be made to reference.
   */
  images: {
    remotePatterns: [{ protocol: "https", hostname: "img.youtube.com" }],
  },
  /**
   * Every one of the 797 old URLs ends in a slash, because that is how WordPress wrote
   * them for fifteen years. With Next's default behaviour `/data/` first 308s to
   * `/data` and only then 301s to `/training/data` — two hops for every inbound link
   * and every search result on the site, which is exactly what a migration must not do.
   *
   * Turning the automatic normalisation off makes the redirect map match the slashed
   * form directly: one hop, always. The trade — `/blog` and `/blog/` both answer 200 —
   * is settled by the canonical link on every route, and it is the friendlier answer
   * anyway: `/blog/` was a real, indexed page on the old site and stays one here.
   */
  skipTrailingSlashRedirect: true,

  async redirects() {
    return map.redirects.map((row) => {
      const { shopOrigin, ...rest } = row;
      // While WooCommerce is alive on its own host, the basket, the checkout and the
      // customer's account belong to it, not to us. Without NEXT_PUBLIC_SHOP_URL these
      // fall back to `/shop`, which at least explains where to buy.
      if (shopOrigin && SHOP_URL) {
        return { ...rest, destination: `${SHOP_URL}${shopOrigin}/`, statusCode: 302 };
      }
      return rest;
    });
  },

  /**
   * 410 Gone for the Malmö theme demos and WordPress's own plumbing. `redirects()`
   * cannot return a 410, so these are rewritten — URL unchanged — onto a route handler
   * that answers 410. See `app/gone/route.ts` and PARITY-PLAN §8.1.
   */
  async rewrites() {
    return {
      beforeFiles: map.gone.map((source) => ({ source, destination: "/gone" })),
      afterFiles: [],
      fallback: [],
    };
  },
};

export default nextConfig;
